/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 
package XMLgui;
import Classes.XML;
import static Classes.XML.XMLbuilder;
import org.w3c.dom.Document;
import Classes.Student;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author a246user
 */
public class NewJFrame extends javax.swing.JFrame {
//        String filePath = "E:\\Java\\Students.xml";
//        Document doc = XMLbuilder(filePath); 
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtDelID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtSearchID = new javax.swing.JTextField();
        txtSearchFName = new javax.swing.JTextField();
        txtSearchLName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbFNLN = new javax.swing.JRadioButton();
        rbID = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        txtAddID = new javax.swing.JTextField();
        txtAddFName = new javax.swing.JTextField();
        txtAddLName = new javax.swing.JTextField();
        btnAddClear = new javax.swing.JButton();
        btnAddAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        txtFilePath = new javax.swing.JTextField();
        btnFilePath = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 438));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete"));
        jPanel3.setPreferredSize(new java.awt.Dimension(187, 140));

        jLabel7.setText("ID");

        btnDelete.setText("Delete");
        btnDelete.setMaximumSize(new java.awt.Dimension(65, 25));
        btnDelete.setMinimumSize(new java.awt.Dimension(65, 25));
        btnDelete.setPreferredSize(new java.awt.Dimension(65, 25));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDelID, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 329, 232, 72));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        jPanel4.setPreferredSize(new java.awt.Dimension(187, 140));

        btnSearch.setText("Search");
        btnSearch.setMaximumSize(new java.awt.Dimension(65, 25));
        btnSearch.setMinimumSize(new java.awt.Dimension(65, 25));
        btnSearch.setPreferredSize(new java.awt.Dimension(65, 25));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSearchClear.setText("Clear");
        btnSearchClear.setMaximumSize(new java.awt.Dimension(65, 25));
        btnSearchClear.setMinimumSize(new java.awt.Dimension(65, 25));
        btnSearchClear.setPreferredSize(new java.awt.Dimension(65, 25));
        btnSearchClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClearActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        buttonGroup3.add(rbFNLN);
        rbFNLN.setText("By Name");
        rbFNLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFNLNActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbID);
        rbID.setText("By ID");
        rbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbID)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchFName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearchID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtSearchLName)
                    .addComponent(rbFNLN))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFNLN)
                    .addComponent(rbID))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 146, 232, 177));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Add"));
        jPanel5.setPreferredSize(new java.awt.Dimension(189, 140));

        btnAddClear.setText("Clear");
        btnAddClear.setMaximumSize(new java.awt.Dimension(65, 25));
        btnAddClear.setMinimumSize(new java.awt.Dimension(65, 25));
        btnAddClear.setPreferredSize(new java.awt.Dimension(65, 25));
        btnAddClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClearActionPerformed(evt);
            }
        });

        btnAddAdd.setText("Add");
        btnAddAdd.setMaximumSize(new java.awt.Dimension(65, 25));
        btnAddAdd.setMinimumSize(new java.awt.Dimension(65, 25));
        btnAddAdd.setPreferredSize(new java.awt.Dimension(65, 25));
        btnAddAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAddActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnAddAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAddFName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtAddID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtAddLName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnAddClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 0, 232, -1));
        jPanel5.getAccessibleContext().setAccessibleName("");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 80, -1));

        txtResults.setEditable(false);
        txtResults.setColumns(20);
        txtResults.setRows(5);
        jScrollPane2.setViewportView(txtResults);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 561, 390));

        txtFilePath.setEditable(false);
        txtFilePath.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtFilePath.setText("Select a database...");
        txtFilePath.setMinimumSize(new java.awt.Dimension(6, 23));
        txtFilePath.setPreferredSize(new java.awt.Dimension(104, 23));
        txtFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePathActionPerformed(evt);
            }
        });
        jPanel1.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 310, 23));

        btnFilePath.setText("Browse");
        btnFilePath.setMaximumSize(new java.awt.Dimension(73, 23));
        btnFilePath.setMinimumSize(new java.awt.Dimension(73, 23));
        btnFilePath.setPreferredSize(new java.awt.Dimension(73, 23));
        btnFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilePathActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 90, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 255));

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 825, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAddActionPerformed
        String filePath = txtFilePath.getText();
        Document doc = XMLbuilder(filePath); 
        txtAddFName.setBorder(null);
        txtAddLName.setBorder(null);
        txtAddID.setBorder(null); 
        txtAddFName.updateUI();
        txtAddLName.updateUI();
        txtAddID.updateUI();
        //Document doc = XMLbuilder(filePath); 
        String id = txtAddID.getText();
        String fName = txtAddFName.getText();
        String lName = txtAddLName.getText();
        
        if (id.isEmpty() ){
            txtAddID.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));        
            
        }if (fName.isEmpty()){
            txtAddFName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));   
        }
        if (lName.isEmpty()){
            txtAddLName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
              
        }
        if (id.isEmpty() || fName.isEmpty() || lName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Invalid Input, All fields must contain data."); 
        }else
        {
        try {
            
                int intID = Integer.parseInt(id);
                List<Student> studentList = XML.XMLsearch("id", intID, "", "", doc);
                for (Student tempStu : studentList )
                {
                    if (tempStu.ID == intID)
                    {
                        txtResults.setText("Duplicate Record Found, Check ID");
                        return;
                    }
                }
                Document localDoc = XML.XMLadd(doc, intID, fName, lName);
                XML.XMLoutput(localDoc, filePath);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID must be an integer, please check your input and try again");            
        }
        txtAddID.setText(null);
        txtAddFName.setText(null);
        txtAddLName.setText(null);
        txtResults.setText(" \" " + id + " " + fName + " " + lName + " \" " + " successfully added.");
        }
    }//GEN-LAST:event_btnAddAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtResults.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClearActionPerformed
        // TODO add your handling code here:
        txtAddID.setText(null);
        txtAddFName.setText(null);
        txtAddLName.setText(null);
        txtAddFName.setBorder(null);
        txtAddLName.setBorder(null);
        txtAddID.setBorder(null); 
        txtAddFName.updateUI();
        txtAddLName.updateUI();
        txtAddID.updateUI();
    }//GEN-LAST:event_btnAddClearActionPerformed

    private void btnSearchClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClearActionPerformed
        txtSearchID.setText(null);
        txtSearchFName.setText(null);
        txtSearchLName.setText(null);
        rbFNLN.setSelected(false);
        rbID.setSelected(false);
        buttonGroup3.clearSelection();
        txtSearchFName.setBorder(null);
        txtSearchLName.setBorder(null);
        txtSearchID.setBorder(null); 
        txtSearchFName.updateUI();
        txtSearchLName.updateUI();
        txtSearchID.updateUI();
        txtSearchID.setEnabled(true);
        txtSearchFName.setEnabled(true);
        txtSearchLName.setEnabled(true);
    }//GEN-LAST:event_btnSearchClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String filePath = txtFilePath.getText();
        Document doc = XMLbuilder(filePath); 
        txtSearchFName.setBorder(null);
        txtSearchLName.setBorder(null);
        txtSearchID.setBorder(null); 
        txtSearchFName.updateUI();
        txtSearchLName.updateUI();
        txtSearchID.updateUI();
        
       //Document doc = XMLbuilder(filePath);
        String criteria;
        String fname = "";
        String lname = "";
        int id = 0;

        if ((rbFNLN.isSelected() && txtSearchFName.getText().isEmpty() && txtSearchLName.getText().isEmpty())){
            txtSearchFName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            txtSearchLName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            txtResults.setText(null);
            txtResults.append("No search criteria has been entered");
        }else if (rbID.isSelected() && txtSearchID.getText().isEmpty()){
            txtResults.setText(null);
            txtResults.append("No search criteria has been entered");
            txtSearchID.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));  
            
    } 
        else {
            if (rbFNLN.isSelected()) {
                criteria = "fnln";
                fname = txtSearchFName.getText();
                lname = txtSearchLName.getText();
            } else if(rbID.isSelected()){
                try {
                    criteria = "id";
                    id = Integer.parseInt(txtSearchID.getText());
                } catch (Exception e) {

                    txtResults.setText("Invalid ID");
                    return;
                }

            }else{
                criteria = null;
                XML.XMLpopulate(doc);
            }

            List<Student> studentList = XML.XMLsearch(criteria, id, fname, lname, doc);

            txtResults.setText(null);
            txtResults.append("ID\t\tFirst Name\t\tLast Name\n");
            txtResults.append("---------------------------------------------------------------------------------------------------------------------------");

            for (Student tempStudent : studentList) {
                txtResults.append("\n" + Integer.toString(tempStudent.ID) + "\t\t" + tempStudent.fName + "\t\t" + tempStudent.lName + "\n");
            }
            txtSearchID.setEnabled(true);
            txtSearchFName.setEnabled(true);
            txtSearchLName.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDActionPerformed
        txtSearchFName.setBorder(null);
        txtSearchLName.setBorder(null);
        txtSearchID.setBorder(null); 
        txtSearchFName.updateUI();
        txtSearchLName.updateUI();
        txtSearchID.updateUI();
        txtSearchID.setEnabled(true);
        txtSearchFName.setEnabled(false);
        txtSearchLName.setEnabled(false);
        txtSearchFName.setText(null);
        txtSearchLName.setText(null);
    }//GEN-LAST:event_rbIDActionPerformed

    private void rbFNLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFNLNActionPerformed
        txtSearchFName.setBorder(null);
        txtSearchLName.setBorder(null);
        txtSearchID.setBorder(null); 
        txtSearchFName.updateUI();
        txtSearchLName.updateUI();
        txtSearchID.updateUI();
        txtSearchID.setEnabled(false);
        txtSearchID.setText(null);
        txtSearchFName.setEnabled(true);
        txtSearchLName.setEnabled(true);
    }//GEN-LAST:event_rbFNLNActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String filePath = txtFilePath.getText();
        Document doc = XMLbuilder(filePath); 
        //Document doc = XMLbuilder(filePath);
        Integer id = Integer.parseInt(txtDelID.getText());
        String guiid = Integer.toString(id);
        XML.XMLdelete(doc, guiid, filePath);                        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
        Desktop.getDesktop().browse(new URL("https://www.yorktech.edu/Course/22864/42822/").toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilePathActionPerformed
        // TODO add your handling code here:
        final JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = chooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
           String filePath = ( chooser.getSelectedFile().toString());
            txtFilePath.setText(filePath);
        }
    }//GEN-LAST:event_btnFilePathActionPerformed

    private void txtFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    
    // <editor-fold defaultstate="collapsed" desc="Variable Declarations">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdd;
    private javax.swing.JButton btnAddClear;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFilePath;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchClear;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbFNLN;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JTextField txtAddFName;
    private javax.swing.JTextField txtAddID;
    private javax.swing.JTextField txtAddLName;
    private javax.swing.JTextField txtDelID;
    private javax.swing.JTextField txtFilePath;
    public javax.swing.JTextArea txtResults;
    private javax.swing.JTextField txtSearchFName;
    private javax.swing.JTextField txtSearchID;
    private javax.swing.JTextField txtSearchLName;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
}
